language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t mnvskzc/docker-react  -f Dockerfile.dev .

script:
  - docker run -e CI=true mnvskzc/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-478902767794"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"     

  # Dockerreact-env.eba-mq6pzdv9.us-east-2.elasticbeanstalk.com  (