language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t mnvskzc/docker-react  -f Dockerfile.dev .

script:
  - docker run -e CI=true mnvskzc/docker-react npm run test -- --coverage

